### PR TITLE
added mmr labels

### PR DESCRIPTION
**Pull request by giordy97**
Labels from MMR driverless team

### CODE REVIEW

**Comment by ddavid** [comment]
Will look into it tomorrow, thank you.
At a first glance, if there are large and big orange cones, please include both as separate classes.

**Comment by ddavid** [comment]
As mentioned above, please adjust the labels to differentiate between small and large cones. It is in your best interest for the competitions ;)
Otherwise, the labels are quite imprecise and there are some mislabeled blue cones. Please review the labeled images.

**Comment by giordy97** [comment]
Hi David, we are currently relabeling the image. We have a question, in this case when the red cones are one in front of another is better to put 3 different label or just one for the cone in front?
Thanks for the advice.
00003878_skid-pad

**Comment by ddavid** [comment]
Hi, firstly I think there are four red/orange cones in the image. You can recognize them by the three bases to the left and one cylinder in excess in the back.
I'd say label the ones where the occlusion isn't substantial (>50%), in this image the two red/orange cones to the front.
The area of the labels for the back two cones would for the most part consist of the cone in their front.

**Comment by giordy97** [comment]
Hy David, in the last commit there are our latest labels, with improved precision and division between orange cones and big ones, hope everythings will be fine this time.

**Comment by ddavid** [comment]
Hi Giordy, will go through them later on tonight and let you know.
Thank you for revising them.

**Comment by ddavid** [comment]
Hi Giordy, everything looking good, but there seems to be a cone with a class index outside of the range from the classes file.
The label for `00004225_skid-pad.txt` is the culprit. As soon as this is fixed, we can move on.

**Comment by giordy97** [comment]
Thank you for the advice, the label should be fixed now, with the right class.

**Comment by ddavid** [comment]
Perfect, I'm currently on a train trip but will add you to the datasets at the next possible time.

**Comment by ddavid** [comment]
Perfect, I'm currently on a train trip with intermittent internet connection but will add you to the datasets at the next possible time.

**Pull request merged**
