### PR TITLE
Add FaSTTUBe

### PR DESCRIPTION
**Pull request by fasttube-dv**
Hello there :)

I added Labels for FaSTTUBe's dataset and updated the docs.

The link to the images as been sent by email.

Cheers!

### CODE REVIEW

**Comment by fasttube-dv** [comment]
Rebased onto current upstream master

**Comment by ddavid** [comment]
Hello Jule,

thank you very much, I received the email and will look into it tomorrow morning. 

Cheers,
David

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddavid** [comment]
The documentation and quality of the labels look good overall.

I'd just ask you to finish labeling the occluded cones in some of the images. 
Since you labeled the yellow cone partially occluded by the blue cone in this image
boxes_fasttube_177
the yellow cone partially occluded by the person's hand should also be labeled consequently.
boxes_fasttube_457

**Comment by GladOSkar** [comment]
Thanks for the feedback! We're on it :)

**Comment by fasttube-dv** [comment]
Thanks for the Feedback! We're on it :)

**Comment by fasttube-dv** [comment]
@ddavid OK our CV people updated the labels accordingly and also did some cleanup. Thanks again!

The photos were also updated, so you'll have to redownload them

**Comment by ddavid** [comment]
Alright, thank you. I’ll have a look later on. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fasttube-dv** [comment]
@ddavid Any updates? Don't want to be pushy but it would be great if we could get access soon-ish.

Thanks a lot!

**Comment by ddavid** [comment]
Hi @fasttube, should be able to review it today. Had two important deadlines at the university yesterday.
Will keep you posted.

**Comment by ddavid** [comment]
Looks good. Thank you very much for your contribution.

**Comment by fasttube-dv** [comment]
Thanks so much for managing this awesome project! All the best from Berlin :)

**Pull request merged**
