### PR TITLE
Added Driverless UPC labels

### PR DESCRIPTION
**Pull request by RogerAylagas**

### CODE REVIEW

**Comment by ddavid** [comment]
Will take a look at the Pull Request today.

**Comment by RogerAylagas** [comment]
Perfect thanks a lot !

[image: photo]
*Roger Aylagas Torres*
Vision Systems Engineer
https://etseib-motorsport.upc.edu/en/driverless
<https://etseib-motorsport.upc.edu/en/driverless-3/>
<https://www.facebook.com/driverlessupcEM/>
<http://twitter.com/etseibmotorspor>
<http://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjF9cWCnqbPAhVGyRQKHadBBjEQFggiMAE&url=https%3A%2F%2Fwww.instagram.com%2Fetseibmotorsport%2F&usg=AFQjCNE8QCpcu2KnyzlhA6N78wGOedt6HA&sig2=-cH0zzkfjxz8yz9qctaStA&bvm=bv.133700528,d.d24>

**Comment by ddavid** [comment]
Hi Roger, the labels are looking good. Could you please update the documentation with regards to your contribution? 
https://github.com/ddavid/fsoco/blob/master/docs/index.md
As soon as that's done I can merge your changes.

**Comment by RogerAylagas** [comment]
Hi David,
I've updated the documentation but there are some conflicts. Will you
resolve them or shall I do it?

[image: photo]
*Roger Aylagas Torres*
Vision Systems Engineer
https://etseib-motorsport.upc.edu/en/driverless
<https://etseib-motorsport.upc.edu/en/driverless-3/>
<https://www.facebook.com/driverlessupcEM/>
<http://twitter.com/etseibmotorspor>
<http://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjF9cWCnqbPAhVGyRQKHadBBjEQFggiMAE&url=https%3A%2F%2Fwww.instagram.com%2Fetseibmotorsport%2F&usg=AFQjCNE8QCpcu2KnyzlhA6N78wGOedt6HA&sig2=-cH0zzkfjxz8yz9qctaStA&bvm=bv.133700528,d.d24>

**Comment by ddavid** [comment]
Hi Roger,
yes I can resolve the merge conflict. Should just be the sequence in which the teams appear in the table

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ddavid** [comment]
Good to go :+1:

**Pull request merged**
