### PR TITLE
CURE Labels

### PR DESCRIPTION
**Pull request by KevS272**
Added the labels for the provided Images

### CODE REVIEW

**Comment by ddavid** [comment]
Looks good at a first glance. Tomorrow I'll have a closer look and hopefully we can get it through right away.

**Comment by ddavid** [comment]
Hi Kevin,
there just seems to be one big orange cone mislabeled as a blue cone. Could you please correct the according file?
Should be this one: `labels/cure/cure labels/cam_left0022.xml`
Thank you for adding the script for voc labels.

**Comment by KevS272** [comment]
Hi,
I corrected the label.
Thanks for checking!

**Comment by ddavid** [comment]
Hi Kevin,
that's what the Merge Requests and the short review are for ;)
Thank you very much for your contribution.

**Comment by ddavid** [comment]
Merging after solving issues with data set sharing.

**Pull request merged**
