### PR TITLE
Upload TUfast labels

### PR DESCRIPTION
**Pull request by AlessandroFerrenti**
Pull Request TUfast

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Alessandro, please update the documentation wrt your contribution. To be more specific, the table and your team's info in the list below.
https://github.com/AlessandroFerrenti/fsoco/blob/master/docs/index.md

**Comment by AlessandroFerrenti** [comment]
I pushed the changes but seems that I do have not the write access to merge the pull request is that right?

**Comment by ddavid** [comment]
Good, I’ll have a look when I’m home. 
That’s right and intended that way, I’ll merge the changes when everything’s done. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ddavid** [comment]
Looking into the labels a bit more atm. Unfortunately wasn't able to do some tests last week.
Will keep you posted.

**Comment by ddavid** [comment]
Hi Alessandro, unfortunately I can't accept the submission as is.
I've written you an e-mail regarding the quality of the labels.

**Comment by AlessandroFerrenti** [comment]
hi David, 
I have uploaded the new labels have a look and tell me if are good enough

**Comment by ddavid** [comment]
Hi Alessandro, I won't be home for the weekend so I'll probably get around to it on Monday morning or late afternoon the soones.
Will keep you posted. Thank you for the update.

**Comment by ddavid** [comment]
Will go through them tomorrow.

**Comment by ddavid** [comment]
Waiting on update regarding label and image changes.
Results with new labels make it look like there's a mismatch in dimensions.

 boxes_000000

**Comment by AlessandroFerrenti** [comment]
Now should be fine

**Comment by ddavid** [comment]
Looks perfect, thank you for the swift fix. The only thing missing is renaming the label files to match the images in your dataset.
e.g. `rename 's/^_//' *.txt` in the label directory on Ubuntu.

**Comment by AlessandroFerrenti** [comment]
Sorry for the late reply, I saw it just now

**Comment by ddavid** [comment]
We're good to go. Thank you for your contribution!

**Pull request merged**
