### PR TITLE
Dynamis PRC dataset submission

### PR DESCRIPTION
**Pull request by manderino1**

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Marco, everything is looking pretty good.
There is one small issue, the big yellow cones in the data set are not labeled as seen in the attached image image 448.
Could you please add labels for the images with big yellow cones and add the class to the classes index text file?

**Comment by manderino1** [comment]
Yes sure, i'll do that this afternoon and commit the changes. Thank you

Il mar 26 nov 2019, 14:07 David Dodel <notifications@github.com> ha scritto:

**Comment by manderino1** [comment]
Hi, i added the class and the cones as requested and also added some missing cones of the other class. I also updated the number of cones in the documentation.
Tell me if there is something else to fix of it's ok now. Thank you

**Comment by ddavid** [comment]
Hi Marco, sorry for the late reply, only came around to take a look at the changes today.
Thank you for making the corrections!
There's just one last thing, are the cones seen in this picture consistently labeled as `orange-cones` throughout the data set?
I ask because in the context of the FSD competitions in Europe, one would assume them to be the `big-orange-cones` that are in your classes file.

boxes_431

**Comment by manderino1** [comment]
Yes, we labelled them all as orange-cones but I can change it if you want them consistent to the other datasets
Just tell me if you prefer and I'll change all the orange-cone class to big-orange-cone

**Comment by ddavid** [comment]
Yes, please do change them, as this could lead to some very weirdly performing models and it's hard to document.
Will go through the changes tomorrow morning.

**Comment by manderino1** [comment]
Do you prefer that i change it just in the class file or all the numbers that refer to the class into the txts?

**Comment by manderino1** [comment]
Ok I did it, it should be ok now

**Comment by ddavid** [comment]
Looks good to go.
Thank you for your contribution!

**Pull request merged**
