### PR TITLE
Add egnition - request

### PR DESCRIPTION
**Pull request by f-cordes**
Everything should be as requested. Would be nice if egnition could be merged into the dataset.

### CODE REVIEW

**Comment by ddavid** [comment]
The request is being reviewed. Some of the labels seem to have a slightly off scaling.

**Comment by f-cordes** [comment]
I updated the labels. Should work now

**Comment by f-cordes** [comment]
Is there by chance any update on the progress?

**Comment by ddavid** [comment]
Hi Florian, I haven't had the chance to review the newest changes this week as I didn't have access to my laptop. Could you please open an issue for the labeling tool error/unexpected in the other repo?

**Pull request merged**
