### PR TITLE
feat(*): added FaSTDa labels and updated docs

### PR DESCRIPTION
**Pull request by lukaskoenen**
Initial FaSTDa-Racing lables and Documentation for Review.

### CODE REVIEW

**Comment by ddavid** [comment]
Hey there Lukas,
firstly the quality of the labels is great on the whole, good job!
It looks like your team had a lot of fun while creating the first samples.

There's a few things before merging though:
- Consistency within your dataset:
boxes_image421
boxes_image422
Although both images above are very similar, the blue cones labeled in the back swap. Why not label both in each image?

boxes_image330
boxes_image608
For the skid-pad images you've labeled even the smallest of cones, but for the sequence coming into and back from Acceleration a lot of cones that look similar are left out.
I'd consider keeping the latter out of your dataset, if you're still above the 600 image contribution threshold without them.

boxes_image759
Along with 817 and 818, I'd expect you to label the cones being carried from how you labeled the rest.

- Wrong labels, the bounding box is put incorrectly:
boxes_image639
boxes_image721

- Wrong Class:
boxes_image785
boxes_image793

Another point is the small orange/red cones from the FSS and FSG footage. I'm afraid those would need to be labeled as otherwise it would be hard to use the dataset together with others. Not having those classes is possible, as long as they don't appear in the dataset's images. The blue-cones in FSS are different enough to be disregarded, since they don't have the white stripe and the hue is quite different.

Lastly, there were a few labels that were mal-formatted. Maybe something went wrong when parsing them?
[mal-formatted.txt](https://github.com/ddavid/fsoco/files/4463553/mal-formatted.txt)

**Comment by lukaskoenen** [comment]
Hi there David, first of all thanks for the detailed feedback. We will look at the problems mentioned above and then provide an updated one. Thanks again and have a nice Easter.

**Comment by lukaskoenen** [comment]
Hi David we hopefully fixed the errors concerning the Dataset. Google Album should be updated aswell.

**Comment by ddavid** [comment]
Hi Lukas, thanks for the update. 
I'm a bit short on time this week because of a practical course at the university, but I'll let you know as soon as I've had the chance to go through the changes.

**Comment by ddavid** [comment]
Unfortunately didn't work out last week. Tomorrow should work :+1:

**Comment by ddavid** [comment]
Hi Lukas, 
the contribution looks excellent! Thank you for putting the extra effort in with the additional small orange cones for the FS Austria and FSG images.
There are just a few labeling mistakes that crept in with the update:
- Two images with some blue cones labeled as yellow cones: `image163` and `image318`
- The yellow cone near the FSG banner on `image317` which is barely recognizable and heavily occluded shouldn't be labeled.
After these small changes, we're good to merge.

**Comment by lukaskoenen** [comment]
Hi David,
thank you, I will take care of fixing the mistakes. I will write a comment again when the frok is updated.

**Comment by lukaskoenen** [comment]
Hi David should all be fixed now.

**Comment by ddavid** [comment]
I'm sorry, I did not see the comment. I will finish it up tomorrow, please excuse the delay.

**Comment by ddavid** [comment]
Perfect, the changes to the last three problematic images look great. Thank you for your contribution.

**Pull request merged**
