### PR TITLE
Add ITU Racing Revised Labels

### PR DESCRIPTION
**Pull request by Isydmr**

### CODE REVIEW

**Comment by Isydmr** [comment]
Hey! Our team checked all labeling errors and we uploaded it again. 

If there are still labeling errors, please, let us know.
Thank you

**Comment by Isydmr** [comment]
Hey! Our team checked all labeling errors and we uploaded it again.

If there are still labeling errors, please, let us know.
Thank you

**Comment by ddavid** [comment]
Hi, thank you for revising the labels.
Will go through it later on tonight.

**Comment by ddavid** [comment]
There are still a few inconsistencies. I'll compile them and send you the feedback tomorrow.

**Comment by Isydmr** [comment]
Ok David, we will try to fix them ASAP. Looking forward for your feedback.

**Comment by ddavid** [comment]
Hi, so one of the issues is the inconsistency with which cones are labeled:

Here, some of the cones on the opposing side are labeled. Judging by their size, compared to the cones you've labeled, a couple more should be labeled on the right hand side.
boxes_cjtrc9qg7c4qe0835ye0slxxt

Another example where none are labeled on the right hand side, although even smaller cones were labeled on the left hand side.
boxes_cjtrc8le4lxua08781epnaiy6

Then there are some images like the one below, where the labels are not precise enough. Please tighten the boxes around the cones, there shouldn't be more background in a bounding box than necessary.
boxes_cjtq70t9wlqit0799vajq3ll0

Finally, there are some very small cones labeled, which by itself isn't bad, but other similarly large cones aren't across the whole dataset and on the same picture. Please make this consistent, as by having a minimal height in pixels (e.g. 10 pixels)
boxes_cjtsg1csem7yy079905f4jrwl

**Comment by ddavid** [comment]
Sorry for the delay, didn't notice the comment wasn't sent on Saturday because of the intermittent internet connection.

**Comment by Isydmr** [comment]
Sorry for the late reply.  Our team has just finished labeling. 

I have uploaded the revised labels. Labels have min. height of 5 pixels and boxes are tightened.

Please see #64 , thank you :)

**Comment by ddavid** [comment]
No problem, sorry for the late reply on my side as well. 
Sounds good, will give you feedback as soon as possible.

**Comment by ddavid** [comment]
Great job improving the labels! 
We're almost there, just two small things left.
There is one label, `cjtsgo1a1ndak0799m1v39ve9.txt`, for which the respective image is missing in the dataset album, as can be seen below:
2020-04-09_Selection-01
Furthermore, there are some inconsistencies in the short sequence before the car starts driving, starting from the following image: `boxes_cjtstp14kx5rw0993o9in29do.jpg`.
Such inconsistencies can happen with different people labeling random samples from the same dataset, but please adjust them to be consistent.
Looking forward to re-integrating your dataset :)

**Comment by Isydmr** [comment]
Okay, we adjusted them again, we made lots of improvements.
For the missing photo, please check your e-mail. 
Thank you for detailed explanations.

**Comment by ddavid** [comment]
Hi İhsan, thank you for sending the missing picture. I've just added it to the album and the additions to the sequence mentioned in my previous comment look good.
Great work on improving the label quality.

**Pull request merged**
