### PR TITLE
UPM Racing labels

### PR DESCRIPTION
**Pull request by crcarloscr**
633 labels have been added, with 6107 cones to labels/upmracing

UPM Racing logo and label format have been added to docs/index.md

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Carlos, still at the ARWo. Will have a look tomorrow.

**Comment by ddavid** [comment]
Got a bit under the weather after the trip, will go through them later on tonight.
Sorry for the delay.

**Comment by ddavid** [comment]
Hi Carlos, overall the labels are of really good quality.
On `00183.txt` there seems to be a wrongly translated label, please fix that one.
Otherwise, could you please remove the labels for all cones that are less than 50% visible (approximate area). Attached are two example images where the partially visible cone shouldn't be labeled, there are more occurrences overall.
boxes_00255

boxes_00271

**Comment by crcarloscr** [comment]
Hi David, 
All labels for cones that are less than 50% visible have been removed.
The label corresponding to image 00183 has also been fixed.
Finally, the number of cones labeled has been modified from index.md due to the removed labels.

I hope every thing is fine this time,
thank you very much.

**Comment by ddavid** [comment]
Hi Carlos,
one last thing, there's one stray yellow-cone label on the top left corner of image nr. 0658.
boxes_00658
Could you also please fix the merge conflict? Should just be the order in the documentation..

**Comment by ddavid** [comment]
As soon as the label without a corresponding cone in the top left corner is fixed, we can merge.
Thank you for taking the time to make the changes.

**Comment by ddavid** [comment]
Thank you very much for the final changes and for the contribution.

**Pull request merged**
