### PR TITLE
Added brt labels

### PR DESCRIPTION
**Pull request by TastySerjo**
Hello, David! 
Could you please check our labels?

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Serjo,
will check them tonight.

**Comment by ddavid** [comment]
Hi Serjo, labels look good, thank you for your contribution.
As soon as you fix the conflict in the docs index file, we can merge.

**Comment by TastySerjo** [comment]
Hi, David, I fixed the conflicts. Is it all right now?

**Comment by ddavid** [comment]
Yes, all good. Thank you.

**Pull request merged**
