### PR TITLE
added labels FE Belgium

### PR DESCRIPTION
**Pull request by WardVer**
Added labels for entry dataset of formula electric Belgium and updated index.md

### CODE REVIEW

**Comment by ddavid** [comment]
Will check it tomorrow. Looks good at a first glance.

**Comment by ddavid** [comment]
Hi Ward, the labels look good, thank you very much for the thorough contribution!

Could you please change the name of the directory where the labels are located to match the name of the album your images are stored in? Furthermore, please add an entry with your team name and logo at the bottom of the documentation for visibility. The design will change in the near future, since the current list doesn't really work with that many contributors.

**Comment by WardVer** [comment]
the changes should have been made now

**Comment by ddavid** [comment]
Thank you, looks good

**Pull request merged**
