### PR TITLE
First 600 labels + info

### PR DESCRIPTION
**Pull request by SiBensberg**
first 600 labels. 
~400 from munich
~200 from us, already uploaded to google.

added LionsRacing logo
updated doku
@ddavid

### CODE REVIEW

**Comment by SiBensberg** [comment]
our 200 pictures are not the best quality and are more for testing the performance on different Resolutions.

**Comment by ddavid** [comment]
Hi Simon,
I'll go through it tonight.

**Comment by ddavid** [comment]
Hi Simon,
there seem to be some inconsistent labels.

boxes_00004015_skid-pad

boxes_00004102_skid-pad

Are just two examples. Maybe some got lost during some data manipulation?

**Comment by SiBensberg** [comment]
@ddavid 
Probably. I don't know how exactly it happened. But i fixed the labels.

**Comment by ddavid** [comment]
Hi Simon, thank you for going through the pictures this swiftly.
Unfortunately taking a closer look at the msc images, there's some issues there as well.

The  missing [cones list](https://github.com/ddavid/fsoco/files/4135436/missing-cones.txt) has the indices of the affected images. Wherever there's no comment, cones very near to the bottom edge or far to the right on the image aren't labeled.
Also, on the captures with the car still standing there are some cones pretty far away that are not consistently labeled, their labels not being present for a sequence of near identical images.
The list is not extensive for time reasons. 
I'll go through all the images again once you're done reviewing the labels on your side.

**Comment by SiBensberg** [comment]
Thank you for the list. I've gone through all pictures and I hope it is ok now. :D

**Comment by ddavid** [comment]
Hi Simon, thank you for going through them. I'll go over the changes today and give you feedback when I'm done.

**Comment by ddavid** [comment]
Looks good to go.

**Pull request merged**
