### PR TITLE
Added Uvigo Labels

### PR DESCRIPTION
**Pull request by ElBley**
Added the labels and logo, updated index.md

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Brais, will look into it tomorrow evening the latest.

**Comment by ddavid** [comment]
Hi Brais, labels look good.
Regarding the documentation, I'm getting a different result for the amount of cones. Could you please check how you got to the documented number?

The command I used to check it was:
`find . -name '*.txt' | xargs wc -l`
In the directory containing only the labels.
Alternatively `cat *.txt | wc -l`

**Comment by ElBley** [comment]
Hey David
I think there might be an issue with your command, since the files don't have an line jump at the end of file. This can cause that doing a line count, the end of a file will be appended to the beginning of the next one. You can verify this by running "cat *.txt" in the directory and analyzing the output. 
The command I run to prevent this was: 
`find . -name '*.txt' | xargs grep "^.*" | wc -l`
If this is an issue I can fix the labels so that they won't append, since I saw that other teams don't have this behavior and I don't want to ruin existing scripts.

**Comment by ddavid** [comment]
Hey Brais, 
thank you for the explanation, makes perfect sense.
Yes, it would be great if you could add the line break at the end of the files.

**Comment by ElBley** [comment]
Ok, I added the line breaks and a script to add them, in case some other team has the same issue

**Comment by ddavid** [comment]
Hi Brais, thank you for performing the changes. Especially for making it easier for people after you to deal with the same issue since it might be sensible to do it your way as well.

**Pull request merged**
