### PR TITLE
Added labels and updated documentation

### PR DESCRIPTION
**Pull request by tobimoo**
Added scuderia mensa labels, team logo and updated index.md

Thank you for organizing this project!

### CODE REVIEW

**Comment by ddavid** [comment]
Hi Tobi, thank you! I will go through the PR tomorrow in the evening. Please excuse the delay.

**Comment by ddavid** [comment]
Hi Tobi, the labels are perfect as is, really good effort!
Unfortunately, I seem to have made a mistake when I composed your dataset and the last ~165 frames are almost identical.
I've scraped together enough images to replace them from our raw data and sent you an e-mail with the dataset.
I'm really sorry for this, I should've checked our raw data better before sending it out to you.

**Comment by ddavid** [comment]
Hi Tobi,
thank you for the swift update to the newly added images.
There seems to be a small issue though, is it possible that during labeling the indices were incremented by one?
That would explain the following effect on the new images:
boxes_front-sun00008
It should be a fast fix, though.

**Comment by tobimoo** [comment]
Hi David,
I fixed the issue in our script. The labels should be fine now!

**Comment by ddavid** [comment]
Hi Tobi,
thank you for the swift fix. We're good to go, thank you for your contribution.

**Pull request merged**
